function LatticeMutation_301(Ind_No)
global POOL_STRUC
global ORG_STRUC
global OFF_STRUC
goodMutant = 0;
goodMutLattice = 0;
count = 0;
while goodMutant + goodMutLattice ~= 2
count = count + 1;
ind = chooseGoodComposition(ORG_STRUC.tournament, POOL_STRUC.POPULATION);
if (count>10) | (ind<0)
USPEXmessage(512,'',0);
Random_301(Ind_No);
break;
end
coor     = POOL_STRUC.POPULATION(ind).COORDINATES;
lat      = POOL_STRUC.POPULATION(ind).LATTICE;
numIons  = POOL_STRUC.POPULATION(ind).numIons;
numBlocks= POOL_STRUC.POPULATION(ind).numBlocks;
order    = POOL_STRUC.POPULATION(ind).order;
[MUT_LAT,strainMatrix, new_Coord] = lattice_atom_Mutation(coor, numIons, lat, order);
coord = new_Coord*MUT_LAT;
[coord, MUT_LAT] = optLattice(coord, MUT_LAT);
new_Coord = coord/MUT_LAT;
goodMutant     = distanceCheck(new_Coord,MUT_LAT, numIons, ORG_STRUC.minDistMatrice);
goodMutLattice = latticeCheck(MUT_LAT);
if goodMutant + goodMutLattice == 2
disp(['Structure ' num2str(Ind_No) ' generated by latmutation']);
info_parents             = struct('parent', {},'strainMatrix', {}, 'enthalpy', {});
info_parents(1).parent   =num2str(POOL_STRUC.POPULATION(ind).Number);
info_parents.enthalpy    = POOL_STRUC.POPULATION(ind).enthalpy;
info_parents.strainMatrix=strainMatrix;
info_parents.strainMatrix=0; 
OFF_STRUC.POPULATION(Ind_No).Parents     = info_parents;
OFF_STRUC.POPULATION(Ind_No).COORDINATES = new_Coord;
OFF_STRUC.POPULATION(Ind_No).LATTICE     = MUT_LAT;
OFF_STRUC.POPULATION(Ind_No).howCome     = ' LatMutate ';
OFF_STRUC.POPULATION(Ind_No).numIons     = numIons;
OFF_STRUC.POPULATION(Ind_No).numBlocks   = numBlocks;
end
end
