#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
USPEX 9.4.4 release
2015 Oganov's Lab. All rights reserved.
"""

# -------------------------------------------------------------------------------
# Variables:

example_name = 'CP2K_300'
columns2check = ['id', 'origin', 'composition', 'enthalpy', 'volume', 'kpoints', 'symm']

empty_dirs = []

files_list = [
    'ANTISEEDS.mat',
    'ANTISEEDS.mat.backup',
    'AntiSeeds',
    'CalcFold1',
    'CalcFold1/atom_forces.xyz',
    'CalcFold1/cc',
    'CalcFold1/cn',
    'CalcFold1/cp2k_options_1',
    'CalcFold1/cp2k_options_2',
    'CalcFold1/cp2k_options_3',
    'CalcFold1/nc',
    'CalcFold1/nn',
    'CalcFold1/nonscc_parameter',
    'CalcFold1/old_USPEX-1.cell',
    'CalcFold1/old_USPEX-pos-1.xyz',
    'CalcFold1/uff_table',
    'CalcFoldTemp',
    'CalcFoldTemp/.data',
    'CalcFoldTemp/.data/data_space.txt',
    'CalcFoldTemp/.data/data_space2d.txt',
    'CalcFoldTemp/.data/data_wyckoff.txt',
    'CalcFoldTemp/findsym.log',
    'CalcFoldTemp/rc.in',
    'CalcFoldTemp/rc.out',
    'CalcFoldTemp/sym.in',
    'CalcFoldTemp/sym.out',
    'CalcFoldTemp/symmetrized.cif',
    'Current_ORG.mat',
    'Current_ORG.mat.backup',
    'Current_POP.mat',
    'Current_POP.mat.backup',
    'INPUT.txt',
    'POSCAR',
    'POSCAR_order',
    'Seeds',
    'Specific',
    'Specific/cc',
    'Specific/cn',
    'Specific/cp2k_options_1',
    'Specific/cp2k_options_2',
    'Specific/cp2k_options_3',
    'Specific/nc',
    'Specific/nn',
    'Specific/nonscc_parameter',
    'Specific/uff_table',
    'Submission',
    'Submission/README',
    'Submission/checkStatusC.m',
    'Submission/checkStatus_local.m',
    'Submission/checkStatus_remote.m',
    'Submission/run-uspex.sh',
    'Submission/submitJob.m',
    'Submission/submitJob_local.m',
    'Submission/submitJob_remote.m',
    'USPEX_IS_DONE',
    'results1',
    'results1/AuxiliaryFiles',
    'results1/BESTIndividuals',
    'results1/BESTgatheredPOSCARS',
    'results1/BESTgatheredPOSCARS_order',
    'results1/E_series.pdf',
    'results1/Energy_vs_N.pdf',
    'results1/Energy_vs_Volume.pdf',
    'results1/Fitness_vs_N.pdf',
    'results1/Individuals',
    'results1/OUTPUT.txt',
    'results1/POOL.mat',
    'results1/POOL.mat.backup',
    'results1/Parameters.txt',
    'results1/Properties',
    'results1/USPEX.mat',
    'results1/USPEX.mat.backup',
    'results1/Variation-Operators.pdf',
    'results1/enthalpies_complete.dat',
    'results1/gatheredPOSCARS',
    'results1/gatheredPOSCARS_order',
    'results1/generation1',
    'results1/generation1/ORG_STRUC.mat',
    'results1/generation1/ORG_STRUC.mat.backup',
    'results1/generation1/POOL.mat',
    'results1/generation1/POOL.mat.backup',
    'results1/generation1/POP_STRUC.mat',
    'results1/generation1/POP_STRUC.mat.backup',
    'results1/generation1/USPEX.mat',
    'results1/generation1/USPEX.mat.backup',
    'results1/generation2',
    'results1/generation2/ORG_STRUC.mat',
    'results1/generation2/ORG_STRUC.mat.backup',
    'results1/generation2/POOL.mat',
    'results1/generation2/POOL.mat.backup',
    'results1/generation2/POP_STRUC.mat',
    'results1/generation2/POP_STRUC.mat.backup',
    'results1/generation2/USPEX.mat',
    'results1/generation2/USPEX.mat.backup',
    'results1/generation3',
    'results1/goodStructures',
    'results1/goodStructures_POSCARS',
    'results1/gatheredPOSCARS_unrelaxed',
    'results1/origin',
    'results1/symmetrized_structures.cif',
]
# -------------------------------------------------------------------------------
