#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
USPEX 9.4.4 release
2015 Oganov's Lab. All rights reserved.
"""

# -------------------------------------------------------------------------------
# Variables:

example_name = 'metadynamics_GULP_300'
columns2check = ['id', 'composition', 'enthalpy', 'volume', 'kpoints', 'symm']

empty_dirs = []

files_list = [
    'CalcFold1',
    'CalcFold1/ginput_1',
    'CalcFold1/ginput_2',
    'CalcFold1/ginput_3',
    'CalcFold1/ginput_4',
    'CalcFold1/goptions_1',
    'CalcFold1/goptions_2',
    'CalcFold1/goptions_3',
    'CalcFold1/goptions_4',
    'CalcFoldTemp',
    'CalcFoldTemp/.data',
    'CalcFoldTemp/.data/data_space2d.txt',
    'CalcFoldTemp/.data/data_space.txt',
    'CalcFoldTemp/.data/data_wyckoff.txt',
    'CalcFoldTemp/findsym.log',
    'CalcFoldTemp/sym.in',
    'CalcFoldTemp/symmetrized.cif',
    'CalcFoldTemp/sym.out',
    'Current_ORG.mat',
    'Current_ORG.mat.backup',
    'Current_POP.mat',
    'Current_POP.mat.backup',
    'INPUT.txt',
    'POSCAR',
    'POSCAR_1',
    'POSCAR_order',
    'results1',
    'results1/AuxiliaryFiles',
    'results1/BestEnthalpy.pdf',
    'results1/BESTgatheredPOSCARS',
    'results1/BESTgatheredPOSCARS_order',
    'results1/BESTgatheredPOSCARS_relaxed',
    'results1/BESTIndividuals',
    'results1/BESTIndividuals_relaxed',
    'results1/BESTpresten.dat',
    'results1/BESTpresten_relaxed.dat',
    'results1/enthalpies_complete.dat',
    'results1/E_series.pdf',
    'results1/gatheredPOSCARS',
    'results1/gatheredPOSCARS_order',
    'results1/gatheredPOSCARS_relaxed',
    'results1/generation0',
    'results1/generation0/ORG_STRUC.mat',
    'results1/generation0/ORG_STRUC.mat.backup',
    'results1/generation0/POP_STRUC.mat',
    'results1/generation0/POP_STRUC.mat.backup',
    'results1/generation0/USPEX.mat',
    'results1/generation0/USPEX.mat.backup',
    'results1/generation1',
    'results1/generation1/ORG_STRUC.mat',
    'results1/generation1/ORG_STRUC.mat.backup',
    'results1/generation1/POP_STRUC.mat',
    'results1/generation1/POP_STRUC.mat.backup',
    'results1/generation1/USPEX.mat',
    'results1/generation1/USPEX.mat.backup',
    'results1/generation2',
    'results1/generation2/ORG_STRUC.mat',
    'results1/generation2/ORG_STRUC.mat.backup',
    'results1/generation2/POP_STRUC.mat',
    'results1/generation2/POP_STRUC.mat.backup',
    'results1/generation2/USPEX.mat',
    'results1/generation2/USPEX.mat.backup',
    'results1/generation3',
    'results1/generation3/ORG_STRUC.mat',
    'results1/generation3/ORG_STRUC.mat.backup',
    'results1/generation3/POP_STRUC.mat',
    'results1/generation3/POP_STRUC.mat.backup',
    'results1/generation3/USPEX.mat',
    'results1/generation3/USPEX.mat.backup',
    'results1/goodStructures',
    'results1/goodStructures_POSCARS',
    'results1/Individuals',
    'results1/Individuals_relaxed',
    'results1/lattice_basic.dat',
    'results1/Lattice_vs_N.pdf',
    'results1/OUTPUT.txt',
    'results1/Parameters.txt',
    'results1/POSCAR_1',
    'results1/presten.dat',
    'results1/presten_relaxed.dat',
    'results1/symmetrized_structures.cif',
    'results1/USPEX.mat',
    'results1/USPEX.mat.backup',
    'Specific',
    'Specific/ginput_1',
    'Specific/ginput_2',
    'Specific/ginput_3',
    'Specific/ginput_4',
    'Specific/goptions_1',
    'Specific/goptions_2',
    'Specific/goptions_3',
    'Specific/goptions_4',
    'Submission',
    'Submission/checkStatusC.m',
    'Submission/checkStatus_local.m',
    'Submission/checkStatus_remote.m',
    'Submission/README',
    'Submission/run-uspex.sh',
    'Submission/submitJob_local.m',
    'Submission/submitJob.m',
    'Submission/submitJob_remote.m',
    'USPEX_IS_DONE',
]
# -------------------------------------------------------------------------------
